api_version = "2025-07"

[[extensions]]
uid = "47580161-e94e-1fee-f14d-2111f5807d13"
type = "ui_extension"
name = "Loyalty Points On Order"
handle = "order-status-rewards"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
network_access = true
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "heading_text"
type = "single_line_text_field"
name = "Heading Text"
description = "Shown above the points count. Default: Points Earned on This Order"

[[extensions.settings.fields]]
key = "referral_reward_text"
type = "single_line_text_field"
name = "Referral Reward Text guest prompt"
description = "e.g. 15% Off Coupon shown to guest users in the login prompt"
